@startuml
[*] --> Created : Create
Created --> RequestSent: Send Request
RequestSent --> AgreementReceived:  On Agreement
RequestSent --> Canceled: Cancel Msg Received
'note on link: Receiver sends cancel msg due to policy
AgreementReceived --> OpeningTxBroadcasted: CreateOpeningTx
AgreementReceived -> SendCancel: Canceled
SendCancel --> Canceled
OpeningTxBroadcasted -left-> TxOpenedMessageSent: SendTxOpenMsg
TxOpenedMessageSent --> ClaimInvPaid: OnClaimInvPaid
TxOpenedMessageSent --> Aborted: OnAbortPayment
TxOpenedMessageSent --> CltvPassed: N blocks pass
CltvPassed --> ClaimedCltv: Claim Cltv
Aborted --> CltvPassed: ClaimWithCltv/send claim msg
ClaimInvPaid --> ClaimedPreimage: OnClaimMsgReceived
@enduml