@startuml
[*] --> Created : Create
Created --> RequestSent: Send Request
RequestSent --> OpeningTxPrepared:  On FeeInvoice
RequestSent --> Canceled: Cancel Msg Received
'note on link: Receiver sends cancel msg due to policy
OpeningTxPrepared --> FeeInvPaid: Pay FeeInvoice
OpeningTxPrepared --> Canceled: Canceled
'note on link: Sender can't/doesn't want to pay the fee
FeeInvPaid --> Broadcasted: OnTxOpenedMsg
Broadcasted --> Confirmed: Wait for confs
Confirmed --> ClaimInvPaid: Pay Claim Inv
Confirmed --> Aborted: Cancel Payment
ClaimInvPaid --> Claimed: Claim Tx
@enduml