@startuml SwapOut
note over Alice, Bob #aqua
Alice wants to swap out: Paying a lightning invoice 
and receiving onchain balance
end note
hnote over Alice: check local channel balance
Alice -> Bob : swap out request
hnote over Bob: check onchain balance, calculate onchain fee, premium
Bob -> Alice : fee response
Alice [#blue]-> Bob: pay fee invoice
hnote over Bob: check if invoice paid, create opening tx
Bob -> Alice : tx opened message
alt alice claims with preimage
hnote over Alice: check if tx has N confirmations
Alice [#blue]-> Bob: pay claim invoice
hnote over Alice: claim tx with preimage
Alice -> Bob: send claim message
else cltv passes
hnote over Bob: claim tx
Bob -> Alice: send claim message
end
@enduml



