name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]  

env:
  SLOW_MACHINE: 1

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        id: setup-go
        with:
          go-version-file: "go.mod"

      - name: Download Go modules
        shell: bash
        if: ${{ steps.setup-go.outputs.cache-hit != 'true' }}
        run: go mod download

      - name: Build
        run: make bins

      - name: Test
        run: make test

  integration-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-vector: [bitcoin-cln, bitcoin-lnd, liquid-cln, liquid-lnd, misc-integration, lwk-cln, lwk-lnd]
      max-parallel: 12
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: nixbuild/nix-quick-install-action@v28
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-${{ runner.os }}-

      - name: Cache compiled binaries
        uses: actions/cache@v4
        with:
          path: |
            ./peerswapd
            ./pscli
            ./test/integration/*.test
          key: binaries-${{ runner.os }}-${{ hashFiles('**/*.go', 'go.mod', 'go.sum') }}
          restore-keys: |
            binaries-${{ runner.os }}-

      - name: Cache test blockchain data
        uses: actions/cache@v4
        with:
          path: |
            ~/.bitcoin
            ~/.elements
            ~/.lightning
          key: blockchain-data-${{ runner.os }}-${{ matrix.test-vector }}-${{ hashFiles('test/integration/setup.go') }}
          restore-keys: |
            blockchain-data-${{ runner.os }}-${{ matrix.test-vector }}-

      - name: Restore and cache Nix store
        uses: nix-community/cache-nix-action@v5
        with:
          # restore and save a cache using this key
          primary-key: nix-${{ runner.os }}-${{ hashFiles('flake.nix', 'flake.lock') }}
          # if there's no cache hit, restore a cache by this prefix
          restore-prefixes-first-match: nix-${{ runner.os }}-
          # collect garbage until Nix store size (in bytes) is at most this number
          # before trying to save a new cache
          gc-max-store-size-linux: 5368709120
          # do purge caches
          purge: true
          # purge all versions of the cache
          purge-prefixes: cache-${{ runner.os }}-
          # created more than this number of seconds ago relative to the start of the `Post Restore` phase
          purge-created: 0
          # except the version with the `primary-key`, if it exists
          purge-primary-key: never
      - run: nix-shell --run "make test-${{matrix.test-vector}}"